### ISSUE TITLE
Taiko V, nus3bank

### ISSUE THREAD

**Issue by dots-tb** [IcySon55/Kuriimu#461]
Issue: bug report
Console: PS Vita
Format extension(s):  nus3bank
Type: archive
Game Name: Taiko no Tatsujin: V Version

First 8 bytes of the file(s):

nus3bank - [4E 55 53 33 7C F9 20 00] - [NUS3|ù .]

More details:

Worked on previous version (had problems with the extensions within the archive though). It no longer works Kuriimu v1.0.12 Hotfix which rewrote nus3bank support. Thanks in advance.

NUS3 - NUS3BANK Sound Archive Manager
---------------------------
System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)

   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)

   at Kontract.Magic.op_Implicit(String s)

   at archive_nintendo.NUS3.GRP..ctor(Stream input)

   at archive_nintendo.NUS3.NUS3..ctor(String filename, Boolean isZlibCompressed)

   at archive_nintendo.NUS3.Nus3Manager.Load(String filename)

   at Karameru.Manager.OpenFile(String filename)
---------------------------
OK   
---------------------------

Sample files (if possible):
https://my.mixtape.moe/ariimx.nus3bank

**Comment by onepiecefreak3** [comment]
Nus3Banks are not really archives, which is why we discontinued its support in Kuriimu2.
Following this, the issue is outdated and does not affect Kuriimu2.
Issue closed.
