### ISSUE TITLE
PSARCs with Japanese filenames can't be opened

### ISSUE THREAD

**Issue by mariomadproductions** [IcySon55/Kuriimu#585]
Issue: bug report
Console: PS4
Format extension(s): psarc 
Type: archive
Game Name: Zero Escape: The Nonary Games

First 8 bytes of the file(s):
psarc - 50 53 41 52 00 01 00 04 - PSAR....

More details:
Can't open archives due to Japanese filenames.
```
---------------------------
PSARC - PlayStation Archive Manager
---------------------------
System.ArgumentException: Illegal characters in path.

   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)

   at System.IO.Path.InternalGetDirectoryName(String path)

   at Karameru.Manager.<>c.<LoadDirectories>b__49_1(ArchiveFileInfo f)

   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)

   at Karameru.Manager.LoadDirectories()

   at Karameru.Manager.OpenFile(String filename)
---------------------------
OK   
---------------------------
```

Sample files (if possible):
https://mega.nz/#!xMwShSDT!On8B5M9pAAHceoZizFldOBTHMhAWrM5Q0MkSETux9_k

**Comment by IcySon55** [comment]
This bug has been fixed, however it's not due to Japanese characters. Instead it's just that the manifest for filenames is using a different delimiter from the common one.
